/**
 * Template-owned config resolution.
 *
 * Store config files are string-generated by StoreForge against whatever
 * template version the store was created with. `resolve*Config` fills every
 * optional field with a sane default so newer template code can rely on a
 * fully-populated shape without ever breaking an older store's config.
 */
import { storeConfig } from "@/config/store";
import { legalConfig } from "@/config/legal";
import { seoConfig } from "@/config/seo";
import { contentConfig } from "@/config/content";
import type {
  ContentConfig,
  HeroStat,
  LegalConfig,
  SeoConfig,
  StoreColors,
  StoreConfig
} from "@/lib/types/config";

const DEFAULT_COLORS: StoreColors = {
  primary: "#000000",
  secondary: "#f0f0f0",
  accent: "#ff3333",
  background: "#ffffff",
  foreground: "#000000",
  muted: "#666666"
};

export interface ResolvedStoreConfig {
  name: string;
  tagline: string;
  logo: { src: string; alt: string };
  favicon: string;
  colors: StoreColors;
  fonts: { heading: string; body: string };
  currency: string;
  announcement: { enabled: boolean; text: string; href: string };
  socials: { instagram: string; tiktok: string; x: string; facebook: string };
  hero: { image: string; headline: string; subtext: string; stats: HeroStat[] };
}

export function resolveStoreConfig(config: StoreConfig = storeConfig): ResolvedStoreConfig {
  return {
    name: config.name || "Store",
    tagline: config.tagline ?? "",
    logo: {
      src: config.logo?.src ?? "/branding/logo.svg",
      alt: config.logo?.alt ?? config.name ?? "Store"
    },
    favicon: config.favicon ?? "/favicon.ico",
    colors: { ...DEFAULT_COLORS, ...config.colors },
    fonts: {
      heading: config.fonts?.heading ?? "Archivo Black",
      body: config.fonts?.body ?? "Inter"
    },
    currency: config.currency ?? "USD",
    announcement: {
      enabled: config.announcement?.enabled ?? false,
      text: config.announcement?.text ?? "",
      href: config.announcement?.href ?? ""
    },
    socials: {
      instagram: config.socials?.instagram ?? "",
      tiktok: config.socials?.tiktok ?? "",
      x: config.socials?.x ?? "",
      facebook: config.socials?.facebook ?? ""
    },
    hero: {
      image: config.hero?.image ?? "",
      headline: config.hero?.headline ?? config.tagline ?? config.name ?? "Store",
      subtext: config.hero?.subtext ?? "",
      stats: config.hero?.stats ?? []
    }
  };
}

export interface ResolvedLegalConfig {
  companyName: string;
  legalName: string;
  address: { line1: string; line2: string; city: string; region: string; postalCode: string; country: string };
  emails: { support: string; legal: string };
  phone: string;
  policies: { returnWindowDays: number; processingTimeDays: number; shipFromCountry: string };
}

export function resolveLegalConfig(config: LegalConfig = legalConfig): ResolvedLegalConfig {
  return {
    companyName: config.companyName || "This Store",
    legalName: config.legalName ?? config.companyName ?? "This Store",
    address: {
      line1: config.address?.line1 ?? "",
      line2: config.address?.line2 ?? "",
      city: config.address?.city ?? "",
      region: config.address?.region ?? "",
      postalCode: config.address?.postalCode ?? "",
      country: config.address?.country ?? ""
    },
    emails: {
      support: config.emails?.support ?? "",
      legal: config.emails?.legal ?? config.emails?.support ?? ""
    },
    phone: config.phone ?? "",
    policies: {
      returnWindowDays: config.policies?.returnWindowDays ?? 30,
      processingTimeDays: config.policies?.processingTimeDays ?? 2,
      shipFromCountry: config.policies?.shipFromCountry ?? ""
    }
  };
}

export interface ResolvedSeoConfig {
  defaultTitle: string;
  titleTemplate: string;
  description: string;
  ogImage: string;
  twitterHandle: string;
}

export function resolveSeoConfig(config: SeoConfig = seoConfig): ResolvedSeoConfig {
  return {
    defaultTitle: config.defaultTitle || "Store",
    titleTemplate: config.titleTemplate ?? `%s | ${config.defaultTitle || "Store"}`,
    description: config.description ?? "",
    ogImage: config.ogImage ?? "/branding/og-image.png",
    twitterHandle: config.twitterHandle ?? ""
  };
}

export interface ResolvedContentConfig {
  testimonials: NonNullable<ContentConfig["testimonials"]>;
  brands: NonNullable<ContentConfig["brands"]>;
  productReviews: NonNullable<ContentConfig["productReviews"]>;
}

export function resolveContentConfig(config: ContentConfig = contentConfig): ResolvedContentConfig {
  return {
    testimonials: config.testimonials ?? [],
    brands: config.brands ?? [],
    productReviews: config.productReviews ?? {}
  };
}
