/**
 * Template-owned config resolution.
 *
 * Store config files are string-generated by StoreForge against whatever
 * template version the store was created with. `resolve*Config` fills every
 * optional field with a sane default so newer template code can rely on a
 * fully-populated shape without ever breaking an older store's config.
 */
import { storeConfig } from "@/config/store";
import { legalConfig } from "@/config/legal";
import { seoConfig } from "@/config/seo";
import { contentConfig } from "@/config/content";
import type {
  AnnouncementItem,
  ContentConfig,
  HeroConfig,
  HeroStat,
  LegalConfig,
  SeoConfig,
  StoreColors,
  StoreConfig
} from "@/lib/types/config";

const DEFAULT_COLORS: StoreColors = {
  primary: "#000000",
  secondary: "#f0f0f0",
  accent: "#ff3333",
  background: "#ffffff",
  foreground: "#000000",
  muted: "#666666",
  heroBackground: "#f0f0f0",
  announcementBackground: "#000000"
};

/** Normalized hero carousel — null means "no carousel configured / nothing usable in it", i.e. render the standard hero. */
export type ResolvedHeroCarousel =
  | { type: "products"; productHandles: string[] }
  | { type: "images"; images: Array<{ image: string; alt: string; href: string }> };

const HERO_CAROUSEL_MAX_ITEMS = 6;

function resolveHeroCarousel(carousel: HeroConfig["carousel"]): ResolvedHeroCarousel | null {
  if (carousel?.type === "products") {
    const productHandles = (carousel.productHandles ?? []).filter(Boolean).slice(0, HERO_CAROUSEL_MAX_ITEMS);
    return productHandles.length > 0 ? { type: "products", productHandles } : null;
  }
  if (carousel?.type === "images") {
    const images = (carousel.images ?? [])
      .filter((item) => item.image)
      .slice(0, HERO_CAROUSEL_MAX_ITEMS)
      .map((item) => ({ image: item.image, alt: item.alt ?? "", href: item.href ?? "" }));
    return images.length > 0 ? { type: "images", images } : null;
  }
  return null;
}

export interface ResolvedStoreConfig {
  name: string;
  tagline: string;
  logo: { src: string; alt: string };
  favicon: string;
  colors: StoreColors;
  fonts: { heading: string; body: string };
  customFonts: { heading?: { src: string; format?: string }; body?: { src: string; format?: string } };
  currency: string;
  announcement: { enabled: boolean; items: AnnouncementItem[] };
  socials: { instagram: string; tiktok: string; x: string; facebook: string };
  hero: {
    image: string;
    headline: string;
    subtext: string;
    stats: HeroStat[];
    productHandle: string;
    carousel: ResolvedHeroCarousel | null;
  };
}

export function resolveStoreConfig(config: StoreConfig = storeConfig): ResolvedStoreConfig {
  return {
    name: config.name || "Store",
    tagline: config.tagline ?? "",
    logo: {
      src: config.logo?.src ?? "/branding/logo.svg",
      alt: config.logo?.alt ?? config.name ?? "Store"
    },
    favicon: config.favicon ?? "/favicon.ico",
    colors: {
      ...DEFAULT_COLORS,
      ...config.colors,
      // Unset in old configs → keep the pre-existing look (hero shared the `secondary` surface).
      heroBackground: config.colors?.heroBackground ?? config.colors?.secondary ?? DEFAULT_COLORS.secondary,
      // Unset in old configs → keep the pre-existing look (bar shared the `primary` surface).
      announcementBackground: config.colors?.announcementBackground ?? config.colors?.primary ?? DEFAULT_COLORS.primary
    },
    fonts: {
      heading: config.fonts?.heading ?? "Archivo Black",
      body: config.fonts?.body ?? "Inter"
    },
    customFonts: {
      heading: config.fonts?.customHeading,
      body: config.fonts?.customBody
    },
    currency: config.currency ?? "USD",
    announcement: {
      enabled: config.announcement?.enabled ?? false,
      items: config.announcement?.items ?? []
    },
    socials: {
      instagram: config.socials?.instagram ?? "",
      tiktok: config.socials?.tiktok ?? "",
      x: config.socials?.x ?? "",
      facebook: config.socials?.facebook ?? ""
    },
    hero: {
      image: config.hero?.image ?? "",
      headline: config.hero?.headline ?? config.tagline ?? config.name ?? "Store",
      subtext: config.hero?.subtext ?? "",
      stats: config.hero?.stats ?? [],
      productHandle: config.hero?.productHandle ?? "",
      carousel: resolveHeroCarousel(config.hero?.carousel)
    }
  };
}

export interface ResolvedLegalConfig {
  companyName: string;
  legalName: string;
  address: { line1: string; line2: string; city: string; region: string; postalCode: string; country: string };
  emails: { support: string; legal: string };
  phone: string;
  governingLaw: string;
  paymentProcessor: string;
  policies: {
    returnWindowDays: number;
    processingTimeDays: number;
    shipFromCountry: string;
    freeShipping: boolean;
    deliveryEstimate: string;
    orderCutoffTime: string;
    damageReportHours: number;
    refundProcessingEstimate: string;
  };
}

export function resolveLegalConfig(config: LegalConfig = legalConfig): ResolvedLegalConfig {
  return {
    companyName: config.companyName || "This Store",
    legalName: config.legalName ?? config.companyName ?? "This Store",
    address: {
      line1: config.address?.line1 ?? "",
      line2: config.address?.line2 ?? "",
      city: config.address?.city ?? "",
      region: config.address?.region ?? "",
      postalCode: config.address?.postalCode ?? "",
      country: config.address?.country ?? ""
    },
    emails: {
      support: config.emails?.support ?? "",
      legal: config.emails?.legal ?? config.emails?.support ?? ""
    },
    phone: config.phone ?? "",
    governingLaw: config.governingLaw ?? config.address?.country ?? "",
    paymentProcessor: config.paymentProcessor ?? "",
    policies: {
      returnWindowDays: config.policies?.returnWindowDays ?? 30,
      processingTimeDays: config.policies?.processingTimeDays ?? 2,
      shipFromCountry: config.policies?.shipFromCountry ?? "",
      freeShipping: config.policies?.freeShipping ?? false,
      deliveryEstimate: config.policies?.deliveryEstimate ?? "",
      orderCutoffTime: config.policies?.orderCutoffTime ?? "",
      damageReportHours: config.policies?.damageReportHours ?? 48,
      refundProcessingEstimate: config.policies?.refundProcessingEstimate ?? ""
    }
  };
}

export interface ResolvedSeoConfig {
  defaultTitle: string;
  titleTemplate: string;
  description: string;
  ogImage: string;
  twitterHandle: string;
  googleSiteVerification: string;
}

export function resolveSeoConfig(config: SeoConfig = seoConfig): ResolvedSeoConfig {
  return {
    defaultTitle: config.defaultTitle || "Store",
    titleTemplate: config.titleTemplate ?? `%s | ${config.defaultTitle || "Store"}`,
    description: config.description ?? "",
    ogImage: config.ogImage ?? "/branding/og-image.png",
    twitterHandle: config.twitterHandle ?? "",
    googleSiteVerification: config.googleSiteVerification ?? ""
  };
}

export interface ResolvedContentConfig {
  testimonials: NonNullable<ContentConfig["testimonials"]>;
  brands: NonNullable<ContentConfig["brands"]>;
  productReviews: NonNullable<ContentConfig["productReviews"]>;
  productFaqs: NonNullable<ContentConfig["productFaqs"]>;
  faqs: NonNullable<ContentConfig["faqs"]>;
  gallery: NonNullable<ContentConfig["gallery"]>;
  trustBar: NonNullable<ContentConfig["trustBar"]>;
  featureCards: NonNullable<ContentConfig["featureCards"]>;
}

export function resolveContentConfig(config: ContentConfig = contentConfig): ResolvedContentConfig {
  return {
    testimonials: config.testimonials ?? [],
    brands: config.brands ?? [],
    productReviews: config.productReviews ?? {},
    productFaqs: config.productFaqs ?? {},
    faqs: config.faqs ?? [],
    gallery: config.gallery ?? [],
    trustBar: config.trustBar ?? [],
    featureCards: config.featureCards ?? []
  };
}
